// code/primer-batch/clock/world-clock-v3/src/app/clock/clock.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-clock',
  templateUrl: './clock.component.html',
  styleUrls: ['./clock.component.css']
})
export class ClockComponent implements OnInit {

  @Input()
  timeZone = "";

  time = ""

  constructor() { }

  ngOnInit(): void {
    setInterval(() => {
      this.time = new Date().toLocaleTimeString('en-US', { timeZone: this.timeZone })
    }, 1000);
  }

}

<div class="card">
    <div class="card-header">{{timeZone}}</div>
    <div class="card-body">
        <span class="badge bg-danger">{{time}}</span>
    </div>
</div>

// code/5-web-ui-frameworks/1-why-we-need-frameworks/2-react-clock-ui/src/Clock.js
import React, { useEffect, useState } from 'react';

function Clock(props) {
    let { timeZone } = props
    let [time, setTime] = useState();
    useEffect(() => {
        setInterval(() => {
            let t = new Date().toLocaleTimeString('en-US', { timeZone })
            setTime(t)
        }, 1000)
    }, [])
    return (
        <div className="card">
            <div className="card-header">{timeZone}</div>
            <div className="card-body">
                <span className="badge bg-danger">
                    {time}
                </span>
            </div>
        </div>
    )
}

export { Clock };
